# Generated by Django 5.1.2 on 2025-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicription', models.TextField(blank=True, null=True)),
                ('image_post', models.ImageField(upload_to='posts/')),
            ],
        ),
    ]
