# Generated by Django 5.1.2 on 2025-04-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_d', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_data',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dicription',
            new_name='description',
        ),
    ]
