# Generated by Django 5.1.2 on 2025-04-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_d', '0003_post_user_alter_post_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_post',
            new_name='image',
        ),
    ]
