# -*- coding: utf-8 -*-
"""matplotli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIMNdNmeGK72dsOexb-dYjWvGHwuRoUM
"""

import matplotlib.pyplot as plt
from matplotlib import style
from mpl_toolkits.mplot3d import Axe

plt.plot([3, 2, 3, 4], [1, 4, 9, 16])
x = [1,2,4,5]
y = [1,4,9,16]
x1 = [1,2,3]
y1 = [3,5,9]
z1 = [1,2,3,1]

plt.plot(x, z1)
plt.plot(x1, y1, marker = 'o')
plt.title("basic")
plt.xlabel("this is x")
plt.ylabel("this is y")
plt.style.use('ggplot')
plt.scatter(x, y)
plt.show()

x = [1,2,3]
y = [2,3,4]
plt.bar(x,y)
plt.show()

import numpy as np

data = np.random.normal(170, 10, 250)

plt.hist(data)
# plt.pie(data)
plt.plot(data)
plt.show()
plt.save()

x = np.array([1,23,2])
y = np.array([2,5,8])
plt.bar(y,x , color = "#4CAF50")
plt.show()

#if we give non-integerdata type to the system they provided as the error so we need to give the hieghit
#or one more thing barh reffer to the horizontal

x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.barh(x, y, height = 0.1)
plt.show()

