# -*- coding: utf-8 -*-
"""pandas_mtplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/raritto-1/e67fcb5f7fc447adb30ef8009501a3b0/pandas_mtplotlib.ipynb
"""

import pandas as pd
import matplotlib as mtl
import numpy as np

dict1 = {
    "name": ["lalit", "punit" , "shyam", "ram"],
    "age" : [23,23,52,100],
    "marks" : [100,200,300,500]
}

df = pd.DataFrame(dict1)



file = pd.read_csv('friends.csv', index_col = 0)

df.head()  # First 5 rows
df.tail()  # Last 5 rows
df.info()  # Summary of DataFrame
df.describe()  # Statistical summary
df.shape  # Rows, Columns count
df.columns  # Column names
df.dtypes  # Data types of columns

df.describe()

from matplotlib import pyplot as plt
_df_3['age'].plot(kind='line', figsize=(8, 4), title='age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_0['age'].plot(kind='hist', bins=20, title='age')
plt.gca().spines[['top', 'right',]].set_visible(False)

print(df)

df.at[0, "age"] = 39

print(df)

df.index = ["first" , "second", "third", "fourth"]

print(df)

print(df.loc["fourth","age"])

ser = pd.Series(np.random.rand(38))

#datafram randome
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

# print(newdf.arange(30, 38))
print(newdf.loc[30:39])

print(newdf)

pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns

print(newdf)

newdf.head()

newdf.dtypes

newdf.iloc[0,0] = 0.25

newdf.index

newdf.columns

newdf.T

newdf.head()

newdf.columns = list("ABCDE")

newdf.head(2)

newdf.loc[0, "F"] = "alit"

newdf.drop('F',axis=1)

0