# Generated by Django 5.0 on 2024-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=15)),
                ("data", models.TextField()),
                ("day", models.CharField(blank=True, max_length=10)),
                ("time", models.TimeField()),
            ],
        ),
    ]
