# Generated by Django 5.1.2 on 2025-03-30 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_bio_profile_joined_at_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='image_field',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
