# Generated by Django 5.1.2 on 2025-03-30 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_postdata_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='image_field',
            field=models.ImageField(upload_to='static/default-profile.jpg', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
